language: python

sudo: false

matrix:
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5-dev
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.6-dev

addons:
  apt:
    packages:
      - pandoc

install:
  - pandoc --from=markdown --to=rst --output=README README.md
  - pip install -r requirements.txt
  - python setup.py install
  - pip install .
  - pip install coverage

after_success: coverage report

script:
- python -m unittest tests/test_nltk_processor.py
- python -m unittest tests/test_spacy_processor.py
